// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwnbm4t490jIjuFuN3KC-I6IAfMPwSTTI',
    appId: '1:714794753331:web:354e9af55e5c07391f7246',
    messagingSenderId: '714794753331',
    projectId: 'tennisremind',
    authDomain: 'tennisremind.firebaseapp.com',
    storageBucket: 'tennisremind.appspot.com',
    measurementId: 'G-4TQZJE02L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaYqDYfTXNw6dK_2MLugILKDrx1YVw-eI',
    appId: '1:714794753331:android:e5a2a134f9a8bb181f7246',
    messagingSenderId: '714794753331',
    projectId: 'tennisremind',
    storageBucket: 'tennisremind.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArMatjEyW3NKN1yD5e2eD2GHJe-nB8Rao',
    appId: '1:714794753331:ios:6c7a94580c1f21031f7246',
    messagingSenderId: '714794753331',
    projectId: 'tennisremind',
    storageBucket: 'tennisremind.appspot.com',
    iosBundleId: 'com.example.tennisreminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArMatjEyW3NKN1yD5e2eD2GHJe-nB8Rao',
    appId: '1:714794753331:ios:6c7a94580c1f21031f7246',
    messagingSenderId: '714794753331',
    projectId: 'tennisremind',
    storageBucket: 'tennisremind.appspot.com',
    iosBundleId: 'com.example.tennisreminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwnbm4t490jIjuFuN3KC-I6IAfMPwSTTI',
    appId: '1:714794753331:web:1610e739aee5660f1f7246',
    messagingSenderId: '714794753331',
    projectId: 'tennisremind',
    authDomain: 'tennisremind.firebaseapp.com',
    storageBucket: 'tennisremind.appspot.com',
    measurementId: 'G-96908N9Y8Q',
  );
}
